=pod

=encoding utf-8

=head1 NAME

Brocken::Jenny::Linker::DWARF - Debug Information Generator

=head1 DESCRIPTION

Generates DWARF v5 compliant debug sections.

=head2 Sections Generated:

=over

=item * B<.debug_line>: Maps machine code offsets to source lines.

=item * B<.debug_info>: The main Debug Information Entry (DIE) tree.

=item * B<.debug_abbrev>: Definitions of DIE abbreviations.

=item * B<.debug_frame>: Stack unwinding and frame pointer recovery data.

=item * B<.debug_aranges>: Rapid lookup table for address ranges.

=item * B<.debug_names>: Fast, hashed symbol lookup table (new in DWARF 5).

=item * B<.debug_str>: String table for DWARF 5 symbol references.

=item * B<.eh_frame>: Exception handling frame data (LSDA compatible).

=back



=head1 LICENSE & LEGAL

This software is Copyright (c) 2026 by Sanko Robinson.

This is free software. You may use, copy, modify, and distribute it under the terms of either of the following
licenses, at your option:

  The Artistic License 2.0 (GPL Compatible) - see F<LICENSE-A2>

  The MIT License (GPL Compatible) - see F<LICENSE-MIT>

The documentation, including the code examples in it, is licensed under the Creative Commons Attribution 4.0
International license, see F<LICENSE-CC>, when it is used apart from the code.


=head1 AUTHOR

Sanko Robinson - L<https://github.com/sanko>


=cut
