=encoding utf-8

=head1 NAME

Brocken::Katsuro::Platform::MacOS - macOS Platform Abstraction

=head1 DESCRIPTION

Concrete platform class for macOS (Darwin). Provides Mach-O binary format support, macOS-specific syscall numbers (with
0x2000000 64-bit offset), and correct library naming conventions (.dylib). On ARM64 macOS, syscall numbers are passed
in x16 rather than x8.

=head1 METHODS

=head2 is_macos

Returns true (1).

=head2 lib_ext

Returns '.dylib'.

=head2 format

Returns 'macho'.

=head2 syscalls

Returns syscall number tables with the 64-bit offset (0x2000000) applied.

=head2 syscall_num_reg

Returns the register used to pass syscall numbers: rax (x86_64), x16 (aarch64), or a7 (riscv64). Note the x16 vs x8
difference on ARM64 macOS.

=head1 LICENSE

This software is Copyright (c) 2026 by Sanko Robinson.

This is free software, licensed under:

  The Artistic License 2.0 (GPL Compatible)

=head1 AUTHOR

Sanko Robinson <sanko@cpan.org>

=head1 LICENSE & LEGAL

This software is Copyright (c) 2026 by Sanko Robinson.

This is free software. You may use, copy, modify, and distribute it under the terms of either of the following
licenses, at your option:

  The Artistic License 2.0 (GPL Compatible) - see F<LICENSE-A2>

  The MIT License (GPL Compatible) - see F<LICENSE-MIT>

The documentation, including the code examples in it, is licensed under the Creative Commons Attribution 4.0
International license, see F<LICENSE-CC>, when it is used apart from the code.

=head1 AUTHOR

Sanko Robinson - L<https://github.com/sanko>

=cut
