=encoding utf-8

=head1 NAME

Brocken::Katsuro::Platform::MidnightBSD - MidnightBSD Platform

=head1 DESCRIPTION

Concrete platform class for MidnightBSD. Inherits from B<BSD>.

=head1 METHODS

=head2 C<is_midnightbsd( )>

Returns a true value.

=head1 LICENSE

This software is Copyright (c) 2026 by Sanko Robinson.

This is free software, licensed under:

  The Artistic License 2.0 (GPL Compatible)

=head1 AUTHOR

Sanko Robinson <sanko@cpan.org>

=head1 LICENSE & LEGAL

This software is Copyright (c) 2026 by Sanko Robinson.

This is free software. You may use, copy, modify, and distribute it under the terms of either of the following
licenses, at your option:

  The Artistic License 2.0 (GPL Compatible) - see F<LICENSE-A2>

  The MIT License (GPL Compatible) - see F<LICENSE-MIT>

The documentation, including the code examples in it, is licensed under the Creative Commons Attribution 4.0
International license, see F<LICENSE-CC>, when it is used apart from the code.

=head1 AUTHOR

Sanko Robinson - L<https://github.com/sanko>

=cut
