=encoding utf-8

=head1 NAME

Brocken::Katsuro::Platform::Wasm - WebAssembly Platform

=head1 DESCRIPTION

Concrete platform class for WebAssembly (WASI). Uses .wasm extensions and the 'wasm' binary format. No library prefix
is used.

=head1 METHODS

=head2 is_wasm

Returns true (1).

=head2 is_posix

Returns true only when the environment is WASI.

=head2 bin_ext

Returns '.wasm'.

=head2 lib_ext

Returns '.wasm'.

=head2 format

Returns 'wasm'.

=head2 lib_prefix

Returns an empty string.

=head1 LICENSE

This software is Copyright (c) 2026 by Sanko Robinson.

This is free software, licensed under:

  The Artistic License 2.0 (GPL Compatible)

=head1 AUTHOR

Sanko Robinson <sanko@cpan.org>

=head1 LICENSE & LEGAL

This software is Copyright (c) 2026 by Sanko Robinson.

This is free software. You may use, copy, modify, and distribute it under the terms of either of the following
licenses, at your option:

  The Artistic License 2.0 (GPL Compatible) - see F<LICENSE-A2>

  The MIT License (GPL Compatible) - see F<LICENSE-MIT>

The documentation, including the code examples in it, is licensed under the Creative Commons Attribution 4.0
International license, see F<LICENSE-CC>, when it is used apart from the code.

=head1 AUTHOR

Sanko Robinson - L<https://github.com/sanko>

=cut
