=pod

=encoding utf-8

=head1 NAME

Brocken::Katsuro::Platform::Windows - Windows Platform

=head1 DESCRIPTION

Concrete platform class for Windows. Uses PE (Portable Executable) format, .exe binaries, .dll shared libraries, and
.lib static libraries. Not POSIX-compliant. Library prefix is empty (e.g., "kernel32.dll").

=head1 METHODS

=head2 is_windows

Returns true (1).

=head2 is_posix

Returns false (0).

=head2 bin_ext

Returns '.exe'.

=head2 lib_ext

Returns '.dll'.

=head2 format

Returns 'pe'.

=head2 lib_prefix

Returns an empty string.

=head2 static_lib_ext

Returns '.a' for GNU environments, '.lib' otherwise.


=head1 LICENSE & LEGAL

This software is Copyright (c) 2026 by Sanko Robinson.

This is free software. You may use, copy, modify, and distribute it under the terms of either of the following
licenses, at your option:

  The Artistic License 2.0 (GPL Compatible) - see F<LICENSE-A2>

  The MIT License (GPL Compatible) - see F<LICENSE-MIT>

The documentation, including the code examples in it, is licensed under the Creative Commons Attribution 4.0
International license, see F<LICENSE-CC>, when it is used apart from the code.


=head1 AUTHOR

Sanko Robinson - L<https://github.com/sanko>


=cut
