=pod

=encoding utf-8

=head1 NAME

Brocken::Katsuro::Platform::ABI::X86_64 - x86_64 ABI Register Definitions

=head1 DESCRIPTION

Defines the System V AMD64 calling convention register sets: scratch (caller-saved), preserved (callee-saved),
parameter passing, and DWARF register numbering.

=head2 Register Sets

=over

=item * B<Caller-saved>: rax, rcx, rdx, rsi, rdi, r8, r9, r10, r11

=item * B<Callee-saved>: rbx, r12, r13, r14, r15

=item * B<Parameters>: rdi, rsi, rdx, rcx, r8, r9

=item * B<Return>: rax

=item * B<FP return>: xmm0

=item * B<FP caller-saved>: xmm0-xmm15 (all)

=back


=head1 LICENSE & LEGAL

This software is Copyright (c) 2026 by Sanko Robinson.

This is free software. You may use, copy, modify, and distribute it under the terms of either of the following
licenses, at your option:

  The Artistic License 2.0 (GPL Compatible) - see F<LICENSE-A2>

  The MIT License (GPL Compatible) - see F<LICENSE-MIT>

The documentation, including the code examples in it, is licensed under the Creative Commons Attribution 4.0
International license, see F<LICENSE-CC>, when it is used apart from the code.


=head1 AUTHOR

Sanko Robinson - L<https://github.com/sanko>


=cut
