use v5.42;
use Test2::V0 '!subtest';
use Test2::Util::Importer 'Test2::Tools::Subtest' => ( subtest_streamed => { -as => 'subtest' } );
use lib 'lib', '../../../lib', '../../lib', '../lib';
use Brocken;
use Brocken::Lindsay;
no warnings qw[experimental::class experimental::builtin portable];
use feature qw[class];
my $brocken  = Brocken->new();
my $platform = $brocken->platform;

sub test_arith {
    my ( $name, $type, $exit_check ) = @_;
    my $func    = Brocken::Lindsay::IR::Function->new( name => 'math', return_type => $type );
    my $builder = Brocken::Lindsay::IR::Builder->new();
    $builder->position_at_end( $func->append_block('entry') );
    $exit_check->($builder);
    my $codegen = $brocken->codegen;
    my $bytes   = $codegen->emit_function($func);
    ok( length($bytes) > 0, "$name: generated bytes" );
    my $linker = $brocken->linker;
SKIP: {
        skip 'Not native', 1 unless $platform->is_native;
        my $output_file = $brocken->tmpdir . '/arith_test' . $brocken->ext;
        $linker->write_executable( $output_file, $bytes, $platform );
        system $output_file;
        my $exit_code = $? >> 8;
        is( $exit_code, $name->{expected} & 0xFF, "$name->{desc}: exit=$name->{expected}" );
        unlink $output_file;
    }
}
subtest 'i64 signed division (div)' => sub {
    for my $tc (
        [ '  42 /   2 =  21',             42,   2,  21 ],
        [ '  42 /  -2 = -21',             42,  -2, -21 ],
        [ ' -42 /   2 = -21',            -42,   2, -21 ],
        [ ' -42 /  -2 =  21',            -42,  -2,  21 ],
        [ '  -9 /  -1 =   9',            -9,   -1,  9 ],
        [ '   9 /  -1 =  -9',             9,   -1, -9 ],
        [ '  -9 /   1 =  -9',            -9,    1, -9 ],
        [ '   0 /  42 =   0',             0,   42,  0 ],
        [ '1000 /   5 = 200 (exit 200)', 1000,  5, 200 ],
    ) {
        my ( $desc, $l, $r, $exp ) = $tc->@*;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'math', return_type => Brocken::Lindsay::IR::Type::i64() );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        $builder->build_ret(
            $builder->build_div(
                Brocken::Lindsay::IR::Constant->new( type => Brocken::Lindsay::IR::Type::i64(), value => $l ),
                Brocken::Lindsay::IR::Constant->new( type => Brocken::Lindsay::IR::Type::i64(), value => $r ),
                '%r'
            )
        );
        my $bytes = $brocken->codegen->emit_function($func);
        ok( length($bytes) > 0, "$desc: generated bytes" );
    SKIP: {
            skip 'Not native', 1 unless $platform->is_native;
            my $f = $brocken->tmpdir . '/arith_div' . $brocken->ext;
            $brocken->linker->write_executable( $f, $bytes, $platform );
            system $f;
            is( $? >> 8, $exp & 0xFF, "$desc" );
            unlink $f;
        }
    }
};
subtest 'i64 signed remainder (rem)' => sub {
    for my $tc (
        [ '  42 %   5 =   2',  42,  5,  2 ],
        [ ' -42 %   5 =  -2', -42,  5, -2 ],
        [ '  42 %  -5 =   2',  42, -5,  2 ],
        [ ' -42 %  -5 =  -2', -42, -5, -2 ],
        [ ' 100 %   7 =   2', 100,  7,  2 ],
        [ '   0 %  42 =   0',  0,  42,  0 ],
    ) {
        my ( $desc, $l, $r, $exp ) = $tc->@*;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'math', return_type => Brocken::Lindsay::IR::Type::i64() );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        $builder->build_ret(
            $builder->build_rem(
                Brocken::Lindsay::IR::Constant->new( type => Brocken::Lindsay::IR::Type::i64(), value => $l ),
                Brocken::Lindsay::IR::Constant->new( type => Brocken::Lindsay::IR::Type::i64(), value => $r ),
                '%r'
            )
        );
        my $bytes = $brocken->codegen->emit_function($func);
        ok( length($bytes) > 0, "$desc: generated bytes" );
    SKIP: {
            skip 'Not native', 1 unless $platform->is_native;
            my $f = $brocken->tmpdir . '/arith_rem' . $brocken->ext;
            $brocken->linker->write_executable( $f, $bytes, $platform );
            system $f;
            is( $? >> 8, $exp & 0xFF, "$desc" );
            unlink $f;
        }
    }
};
subtest 'i64 unsigned division (udiv / urem)' => sub {
    for my $tc (
        [ 'udiv  42 /   2 =  21', 'udiv', 42,  2, 21 ],
        [ 'urem  42 %   5 =   2', 'urem', 42,  5, 2 ],
        [ 'udiv 100 /   7 =  14', 'udiv', 100, 7, 14 ],
        [ 'urem 100 %   7 =   2', 'urem', 100, 7, 2 ],
    ) {
        my ( $desc, $op, $l, $r, $exp ) = $tc->@*;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'math', return_type => Brocken::Lindsay::IR::Type::i64() );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $method = $op eq 'udiv' ? 'build_udiv' : 'build_urem';
        $builder->build_ret(
            $builder->$method(
                Brocken::Lindsay::IR::Constant->new( type => Brocken::Lindsay::IR::Type::i64(), value => $l ),
                Brocken::Lindsay::IR::Constant->new( type => Brocken::Lindsay::IR::Type::i64(), value => $r ),
                '%r'
            )
        );
        my $bytes = $brocken->codegen->emit_function($func);
        ok( length($bytes) > 0, "$desc: generated bytes" );
    SKIP: {
            skip 'Not native', 1 unless $platform->is_native;
            my $f = $brocken->tmpdir . '/arith_unsigned' . $brocken->ext;
            $brocken->linker->write_executable( $f, $bytes, $platform );
            system $f;
            is( $? >> 8, $exp & 0xFF, "$desc" );
            unlink $f;
        }
    }
};
subtest 'i32 signed division and remainder' => sub {
    for my $tc (
        [ ' 42 /  -2 = -21 (i32)', 'div',  42, -2, -21 ],
        [ '-42 /   2 = -21 (i32)', 'div', -42,  2, -21 ],
        [ ' 42 %   5 =   2 (i32)', 'rem',  42,  5,  2 ],
        [ '-42 %   5 =  -2 (i32)', 'rem', -42,  5, -2 ],
    ) {
        my ( $desc, $op, $l, $r, $exp ) = $tc->@*;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'math', return_type => Brocken::Lindsay::IR::Type::i32() );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $method = $op eq 'div' ? 'build_div' : 'build_rem';
        $builder->build_ret(
            $builder->$method(
                Brocken::Lindsay::IR::Constant->new( type => Brocken::Lindsay::IR::Type::i32(), value => $l ),
                Brocken::Lindsay::IR::Constant->new( type => Brocken::Lindsay::IR::Type::i32(), value => $r ),
                '%r'
            )
        );
        my $bytes = $brocken->codegen->emit_function($func);
        ok( length($bytes) > 0, "$desc: generated bytes" );
    SKIP: {
            skip 'Not native', 1 unless $platform->is_native;
            my $f = $brocken->tmpdir . '/arith_i32' . $brocken->ext;
            $brocken->linker->write_executable( $f, $bytes, $platform );
            system $f;
            is( $? >> 8, $exp & 0xFF, "$desc" );
            unlink $f;
        }
    }
};

# Test that regressions against earlier fixes still hold
subtest 'regression: bitwise ops with negative values' => sub {
    for my $tc (
        [ ' -78 & -78 = -78', 'and', -78, -78, -78 ],
        [ ' -78 | -78 = -78', 'or',  -78, -78, -78 ],
        [ ' -78 ^ -78 =   0', 'xor', -78, -78,  0 ],
        [ ' -78 &   1 =   0', 'and', -78,  1,   0 ],
    ) {
        my ( $desc, $op, $l, $r, $exp ) = $tc->@*;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'math', return_type => Brocken::Lindsay::IR::Type::i64() );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $method = { 'and' => 'build_and', 'or' => 'build_or', 'xor' => 'build_xor' }->{$op};
        $builder->build_ret(
            $builder->$method(
                Brocken::Lindsay::IR::Constant->new( type => Brocken::Lindsay::IR::Type::i64(), value => $l ),
                Brocken::Lindsay::IR::Constant->new( type => Brocken::Lindsay::IR::Type::i64(), value => $r ),
                '%r'
            )
        );
        my $bytes = $brocken->codegen->emit_function($func);
        ok( length($bytes) > 0, "$desc: generated bytes" );
    SKIP: {
            skip 'Not native', 1 unless $platform->is_native;
            my $f = $brocken->tmpdir . '/arith_bitwise' . $brocken->ext;
            $brocken->linker->write_executable( $f, $bytes, $platform );
            system $f;
            is( $? >> 8, $exp & 0xFF, "$desc" );
            unlink $f;
        }
    }
};

# Existing i32 add/sub test
subtest 'i32 add / sub' => sub {
    my $func    = Brocken::Lindsay::IR::Function->new( name => 'math', return_type => Brocken::Lindsay::IR::Type::i32() );
    my $builder = Brocken::Lindsay::IR::Builder->new();
    $builder->position_at_end( $func->append_block('entry') );
    my $v1 = $builder->build_add(
        Brocken::Lindsay::IR::Constant->new( type => Brocken::Lindsay::IR::Type::i32(), value => 40 ),
        Brocken::Lindsay::IR::Constant->new( type => Brocken::Lindsay::IR::Type::i32(), value => 10 ),
        '%v1'
    );
    my $v2 = $builder->build_sub( $v1, Brocken::Lindsay::IR::Constant->new( type => Brocken::Lindsay::IR::Type::i32(), value => 8 ), '%v2' );
    $builder->build_ret($v2);
    my $codegen = $brocken->codegen;
    my $bytes   = $codegen->emit_function($func);
    ok( length($bytes) > 0, 'Generated math bytes for ' . $platform->friendly );
    my $linker = $brocken->linker;
SKIP: {
        skip 'Execution test only supported on native hosts', 2 unless $platform->is_native;
        my $output_file = $brocken->tmpdir . '/math_test' . $brocken->ext;
        $linker->write_executable( $output_file, $bytes, $platform );
        ok( -x $output_file || $platform->is_windows, 'Math binary exists' );
        system $output_file;
        my $exit_code = $? >> 8;
        is( $exit_code, 42, 'Math binary returned 42 on ' . $platform->friendly );
        unlink $output_file;
    }
};
done_testing;
