use v5.42;
use Test2::V0 '!subtest';
use lib 'lib', '../../../lib', '../../lib', '../lib';
use Brocken;
use Brocken::Lindsay;
no warnings qw[experimental::class experimental::builtin portable];
use feature qw[class];
my $brocken  = Brocken->new();
my $platform = $brocken->platform;
my $i64      = Brocken::Lindsay::IR::Type::i64();

# A register-source shift (shl/lshr/ashr with a non-immediate count) is encoded
# with the D3 /ext form, which reads the count from CL, so codegen moves the
# count into rcx right before the shift. That move is invisible to the
# per-function phys_reg destination scan in RegAlloc, so before rcx was reserved
# the allocator could place a live value -- including the shift's own
# destination, which the two-address lowering copies into a fresh register --
# in rcx. The count move then overwrote it, and the shift ended up operating on
# the count instead of the value: shl(2,3) computed 3<<3 = 24.
sub emit {
    my ( $t, $checks ) = @_;
    my $func    = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i64 );
    my $builder = Brocken::Lindsay::IR::Builder->new();
    my $seq     = 0;
    my $nm      = sub { sprintf '%%v%d', $seq++ };
    my $K       = sub { Brocken::Lindsay::IR::Constant->new(@_) };
    $builder->position_at_end( $func->append_block('entry') );
    my $ld = sub {
        my ($value) = @_;
        my $slot = $builder->build_alloca( $t, $nm->() );
        $builder->build_store( $K->( type => $t, value => $value ), $slot );
        return $builder->build_load( $t, $slot, $nm->() );
    };
    my @cmp = $checks->( $builder, $nm, $K, $ld );
    my $all = $cmp[0];
    $all = $builder->build_and( $all, $cmp[$_], $nm->() ) for 1 .. $#cmp;
    my $t_block = $func->append_block('if.then');
    my $f_block = $func->append_block('if.else');
    $builder->build_cond_br( $all, $t_block, $f_block );
    $builder->position_at_end($t_block);
    $builder->build_ret( $K->( type => $i64, value => 42 ) );
    $builder->position_at_end($f_block);
    $builder->build_ret( $K->( type => $i64, value => 0 ) );
    return $brocken->codegen->emit_function($func);
}

sub run {
    my ( $label, $t, $checks ) = @_;
    my $bytes = emit( $t, $checks );
    ok( length($bytes) > 0, "$label: generated bytes" );
SKIP: {
        skip "Execution test only supported on $platform->friendly", 1 unless $platform->is_native;
        my $out = $brocken->tmpdir . "/shiftreg_$label" . $brocken->ext;
        $brocken->linker->write_executable( $out, $bytes, $platform );
        my $rc = system $out;
    SKIP: {
            skip "system() failed to spawn ($!)", 1 if $rc == -1;
            is( $? >> 8, 42, "$label: returned 42" );
        }
        unlink $out;
    }
}

# Arithmetic shift right, with floor semantics so negative operands are covered.
sub ashift {
    my ( $a, $b ) = @_;
    my $d = 2**$b;
    return $a >= 0 ? int( $a / $d ) : -int( ( -$a + $d - 1 ) / $d );
}

# Exhaustive small grid per shift kind. Before the fix, 12 of the 16 shl cases
# were wrong, so the grid has to be broad enough to catch the aliasing.
for my $kind (qw(shl lshr ashr)) {
    my $m        = "build_$kind";
    my @operands = $kind eq 'ashr' ? ( -4, -3, -2, -1, 1, 2, 3, 4 ) : ( 1, 2, 3, 4 );
    run(
        $kind, $i64,
        sub {
            my ( $builder, $nm, $K, $ld ) = @_;
            my @cmp;
            for my $a (@operands) {
                for my $b ( 0 .. 4 ) {
                    my $got  = $builder->$m( $ld->($a), $ld->($b), $nm->() );
                    my $want = $kind eq 'shl' ? $a << $b : ashift( $a, $b );
                    push @cmp, $builder->build_icmp( 'eq', $got, $K->( type => $i64, value => $want ), $nm->() );
                }
            }
            return @cmp;
        }
    );
}

# An immediate count must not be affected: it uses the C1 /ext ib form and never
# touches rcx.
run(
    'shl_imm',
    $i64,
    sub {
        my ( $builder, $nm, $K, $ld ) = @_;
        my @cmp;
        for my $a ( 1 .. 8 ) {
            for my $b ( 0 .. 4 ) {
                my $got = $builder->build_shl( $ld->($a), $K->( type => $i64, value => $b ), $nm->() );
                push @cmp, $builder->build_icmp( 'eq', $got, $K->( type => $i64, value => $a << $b ), $nm->() );
            }
        }
        return @cmp;
    }
);

# Shift results that must stay live alongside other values, so rcx would be a
# tempting register for something the count move could destroy.
run(
    'shift_with_live_values',
    $i64,
    sub {
        my ( $builder, $nm, $K, $ld ) = @_;
        my @live = map { $ld->($_) } 1 .. 8;
        my $acc  = $builder->build_shl( $live[0], $live[1], $nm->() );    # 1 << 2 = 4
        $acc = $builder->build_add( $acc, $live[$_], $nm->() ) for 0 .. $#live;
        my $want = 4;
        $want += $_ for 1 .. 8;
        return ( $builder->build_icmp( 'eq', $acc, $K->( type => $i64, value => $want ), $nm->() ) );
    }
);
done_testing;
