use v5.42;
use Test2::V0 '!subtest';
use lib 'lib', '../../../lib', '../../lib', '../lib';
use Brocken;
use Brocken::Lindsay;
no warnings qw[experimental::class experimental::builtin portable];
use feature qw[class];

my $brocken  = Brocken->new();
my $platform = $brocken->platform;
my $i64     = Brocken::Lindsay::IR::Type::i64();

# Scalar integer min/max. There is no single x86 instruction for a signed or
# unsigned minimum of two GPRs, so the lowerer expands the operation into the
# usual branch-free select: cmp, setl to make an all-ones/all-zeros mask, then
# xor/and/xor to pick the operand. Before the expansion the generic fallback
# emitted a MIR min/max opcode that x86 codegen has no handler for, so the
# operation was silently dropped and the result register still held the
# left-hand operand.

# Ordered operand pairs per width. Both orders are covered because the select is
# not symmetric, and the extremes are included because a mask built from setl is
# only correct if the comparison really is a full 64-bit signed compare -- a
# 32-bit compare truncates INT64_MIN/INT64_MAX to the same value and yields a
# mask of 0 where -1 is required.
my %VALUES = (
    i8  => [ -128, -5, -1, 0, 1, 5, 127 ],
    i16 => [ -32768, -300, -1, 0, 1, 300, 32767 ],
    i32 => [ -2147483648, -5, -1, 0, 1, 5, 2147483647 ],
    i64 => [ -9223372036854775808, -9223372036854775807, -1, 0, 1, 5, 9223372036854775807 ],
);
my %TYPE = (
    i8  => Brocken::Lindsay::IR::Type::i8(),
    i16 => Brocken::Lindsay::IR::Type::i16(),
    i32 => Brocken::Lindsay::IR::Type::i32(),
    i64 => $i64,
);

sub emit {
    my ( $t, $checks ) = @_;
    my $func    = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i64 );
    my $builder = Brocken::Lindsay::IR::Builder->new();
    my $seq     = 0;
    my $nm      = sub { sprintf '%%v%d', $seq++ };
    my $K       = sub { Brocken::Lindsay::IR::Constant->new( @_ ) };
    $builder->position_at_end( $func->append_block('entry') );
    my $ld = sub {
        my ( $value ) = @_;
        my $slot = $builder->build_alloca( $t, $nm->() );
        $builder->build_store( $K->( type => $t, value => $value ), $slot );
        return $builder->build_load( $t, $slot, $nm->() );
    };
    my @cmp = $checks->( $builder, $nm, $K, $ld );
    my $all = $cmp[0];
    $all = $builder->build_and( $all, $cmp[$_], $nm->() ) for 1 .. $#cmp;
    my $t_block = $func->append_block('if.then');
    my $f_block = $func->append_block('if.else');
    $builder->build_cond_br( $all, $t_block, $f_block );
    $builder->position_at_end($t_block);
    $builder->build_ret( $K->( type => $i64, value => 42 ) );
    $builder->position_at_end($f_block);
    $builder->build_ret( $K->( type => $i64, value => 0 ) );
    return $brocken->codegen->emit_function($func);
}

sub run {
    my ( $label, $t, $checks ) = @_;
    my $bytes = emit( $t, $checks );
    ok( length($bytes) > 0, "$label: generated bytes" );
    SKIP: {
        skip "Execution test only supported on $platform->friendly", 1 unless $platform->is_native;
        my $out = $brocken->tmpdir . "/intminmax_$label" . $brocken->ext;
        $brocken->linker->write_executable( $out, $bytes, $platform );
        my $rc = system $out;
        SKIP: {
            skip "system() failed to spawn ($!)", 1 if $rc == -1;
            is( $? >> 8, 42, "$label: returned 42" );
        }
        unlink $out;
    }
}

# A register-source min/max, widened to i64 so the comparison happens at a width
# whose result is observable. Exit codes are 8-bit, so the value can never be
# returned directly.
sub check_ops {
    my ( $builder, $nm, $K, $ld, $t, $kind, $pairs ) = @_;
    my @cmp;
    for my $pair (@$pairs) {
        my ( $a, $b ) = @$pair;
        my $got  = $builder->$kind( $ld->($a), $ld->($b), $nm->() );
        my $want = $kind eq 'build_min' ? ( $a < $b ? $a : $b ) : ( $a > $b ? $a : $b );
        push @cmp,
            $builder->build_icmp( 'eq', $builder->build_sext( $got, $i64, $nm->() ),
            $K->( type => $i64, value => $want ), $nm->() );
    }
    return @cmp;
}

# Ordered pairs that include the width's extremes in both positions, plus equal
# operands. Eight comparisons per function keeps the expected-value registers
# live across the whole body, which is where an incorrect mask or a clobbered
# compare result shows up.
sub pairs_for {
    my (@v) = @_;
    my ( $lo, $hi ) = ( $v[0], $v[-1] );
    return (
        [ $lo, $hi ], [ $hi, $lo ], [ $lo, $lo ], [ $hi, $hi ],
        [ -1,  1 ], [ 1, -1 ], [ $lo, 0 ], [ 0, $hi ],
    );
}

for my $tname (qw(i8 i16 i32 i64)) {
    my $t     = $TYPE{$tname};
    my $pairs = [ pairs_for( @{ $VALUES{$tname} } ) ];
    for my $kind (qw(build_min build_max)) {
        run( "${tname}_${kind}", $t,
            sub { check_ops( @_[0 .. 3], $t, $kind, $pairs ) } );
    }

    # Immediate operands must go through the same expansion, so a constant bound
    # is exercised in every position.
    run( "${tname}_imm", $t, sub {
        my ( $builder, $nm, $K, $ld ) = @_;
        my ( $lo, $hi ) = ( $VALUES{$tname}[0], $VALUES{$tname}[-1] );

        # Half of these expect the left operand and half expect the right, so
        # this case still discriminates if the result is left untouched: an
        # unexpanded min/max leaves the left-hand value in the result register,
        # which silently satisfies only the "want is the LHS" half.
        my @spec = (
            [ 'build_min', $K->( type => $t, value => $lo ), $ld->($hi), $lo ],
            [ 'build_min', $K->( type => $t, value => $hi ), $ld->($lo), $lo ],
            [ 'build_min', $ld->($lo),  $K->( type => $t, value => $hi ), $lo ],
            [ 'build_min', $ld->($hi),  $K->( type => $t, value => $lo ), $lo ],
            [ 'build_max', $K->( type => $t, value => $hi ), $ld->($lo), $hi ],
            [ 'build_max', $K->( type => $t, value => $lo ), $ld->($hi), $hi ],
            [ 'build_max', $ld->($hi),  $K->( type => $t, value => $lo ), $hi ],
            [ 'build_max', $ld->($lo),  $K->( type => $t, value => $hi ), $hi ],
        );
        return map {
            my ( $kind, $x, $y, $want ) = @$_;
            my $got = $builder->$kind( $x, $y, $nm->() );
            $builder->build_icmp( 'eq', $builder->build_sext( $got, $i64, $nm->() ),
                $K->( type => $i64, value => $want ), $nm->() );
        } @spec;
    } );
}

done_testing;
