use v5.42;
use Test2::V0 '!subtest';
use Test2::Util::Importer 'Test2::Tools::Subtest' => ( subtest_streamed => { -as => 'subtest' } );
use lib 'lib', '../../../lib', '../../lib', '../lib';
use Test2::Tools::Brocken;
use Brocken;
use Brocken::Lindsay;
use Brocken::Katsuro;
use Brocken::Jenny;
no warnings qw[experimental::class experimental::builtin portable];
use feature qw[class];

my $brocken   = Brocken->new();
my $platform  = $brocken->platform;
my $lowerer_x = 'Brocken::Jenny::Lowerer::X86_64';
my $plat_x    = Brocken::Katsuro::Platform::parse('x86_64-unknown-linux-gnu');

my $i1  = Brocken::Lindsay::IR::Type::i1();
my $i8  = Brocken::Lindsay::IR::Type::i8();
my $i16 = Brocken::Lindsay::IR::Type::i16();
my $i32 = Brocken::Lindsay::IR::Type::i32();
my $i64 = Brocken::Lindsay::IR::Type::i64();


# Lowerer tests (MIR-level verification)

subtest 'Lowerer: alloca size rounds up for sub-byte types' => sub {
    my $check = sub {
        my ( $type, $expected_size, $label ) = @_;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'test', return_type => $i64 );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        $builder->build_alloca( $type, '%ptr' );
        $builder->build_ret( Brocken::Lindsay::IR::Constant->new( type => $i64, value => 0 ) );
        my $lowerer   = $lowerer_x->new( platform => $plat_x );
        my $mf        = $lowerer->lower($func);
        my @allocas   = grep { $_->opcode eq 'alloca' } $mf->blocks->[0]->instructions->@*;
        is( $allocas[0]->operands->[1]->value, $expected_size, "$label: alloca $expected_size bytes" );
    };
    $check->( $i1,  1, 'i1' );
    $check->( $i8,  1, 'i8' );
    $check->( $i16, 2, 'i16' );
    $check->( $i32, 4, 'i32' );
    $check->( $i64, 8, 'i64' );
};

subtest 'Lowerer: store memory operand type matches alloca type' => sub {
    my $check = sub {
        my ( $alloc_type, $val_type, $expected_bits, $label ) = @_;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'test', return_type => $i64 );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $ptr = $builder->build_alloca( $alloc_type, '%ptr' );
        $builder->build_store( Brocken::Lindsay::IR::Constant->new( type => $val_type, value => 42 ), $ptr );
        $builder->build_ret( Brocken::Lindsay::IR::Constant->new( type => $i64, value => 0 ) );
        my $lowerer = $lowerer_x->new( platform => $plat_x );
        my $mf      = $lowerer->lower($func);
        my @stores  = grep { $_->opcode eq 'store' || $_->opcode eq 'store_imm' } $mf->blocks->[0]->instructions->@*;
        is( scalar @stores,                            1,                "$label: store instruction created" );
        is( $stores[0]->operands->[0]->type->bits,     $expected_bits,   "$label: mem operand is ${expected_bits}-bit" );
    };
    $check->( $i1,  $i64, 1,  'i1 alloca with i64 value' );
    $check->( $i8,  $i64, 8,  'i8 alloca with i64 value' );
    $check->( $i16, $i64, 16, 'i16 alloca with i64 value' );
    $check->( $i32, $i64, 32, 'i32 alloca with i64 value' );
    $check->( $i64, $i64, 64, 'i64 alloca with i64 value' );
};


# Execution tests (compile -> run -> verify exit code)

subtest 'i8 alloca / store / load / zext / return' => sub {
    SKIP: {
        skip 'Execution test only supported on native hosts', 3 unless $platform->is_native;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i64 );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $ptr = $builder->build_alloca( $i8, '%ptr' );
        $builder->build_store( Brocken::Lindsay::IR::Constant->new( type => $i8, value => 42 ), $ptr );
        my $val = $builder->build_load( $i8, $ptr, '%val' );
        $builder->build_ret( $builder->build_zext( $val, $i64, '%ext' ) );
        my $codegen     = $brocken->codegen;
        my $bytes       = $codegen->emit_function($func);
        ok( length($bytes) > 0, 'i8: generated bytes' );
        my $output_file = $brocken->tmpdir . '/width_i8' . $brocken->ext;
        $brocken->linker->write_executable( $output_file, $bytes, $platform );
        run_exec( $output_file, expected_exit => 42, platform => $platform, name => 'i8 store/load returned 42' );
    }
};

subtest 'i16 alloca / store / load / zext / return' => sub {
    SKIP: {
        skip 'Execution test only supported on native hosts', 3 unless $platform->is_native;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i64 );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $ptr = $builder->build_alloca( $i16, '%ptr' );
        $builder->build_store( Brocken::Lindsay::IR::Constant->new( type => $i16, value => 200 ), $ptr );
        my $val = $builder->build_load( $i16, $ptr, '%val' );
        $builder->build_ret( $builder->build_zext( $val, $i64, '%ext' ) );
        my $codegen     = $brocken->codegen;
        my $bytes       = $codegen->emit_function($func);
        ok( length($bytes) > 0, 'i16: generated bytes' );
        my $output_file = $brocken->tmpdir . '/width_i16' . $brocken->ext;
        $brocken->linker->write_executable( $output_file, $bytes, $platform );
        run_exec( $output_file, expected_exit => 200, platform => $platform, name => 'i16 store/load returned 200' );
    }
};

subtest 'i32 alloca / store / load / return' => sub {
    SKIP: {
        skip 'Execution test only supported on native hosts', 3 unless $platform->is_native;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i64 );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $ptr = $builder->build_alloca( $i32, '%ptr' );
        $builder->build_store( Brocken::Lindsay::IR::Constant->new( type => $i32, value => 200 ), $ptr );
        my $val = $builder->build_load( $i32, $ptr, '%val' );
        $builder->build_ret( $builder->build_zext( $val, $i64, '%ext' ) );
        my $codegen     = $brocken->codegen;
        my $bytes       = $codegen->emit_function($func);
        ok( length($bytes) > 0, 'i32: generated bytes' );
        my $output_file = $brocken->tmpdir . '/width_i32' . $brocken->ext;
        $brocken->linker->write_executable( $output_file, $bytes, $platform );
        run_exec( $output_file, expected_exit => 200, platform => $platform, name => 'i32 store/load returned 200' );
    }
};

subtest 'i32 alloca / store negative / load sext / return' => sub {
    SKIP: {
        skip 'Execution test only supported on native hosts', 3 unless $platform->is_native;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i64 );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $ptr = $builder->build_alloca( $i32, '%ptr' );
        $builder->build_store( Brocken::Lindsay::IR::Constant->new( type => $i32, value => -1 ), $ptr );
        my $val = $builder->build_load( $i32, $ptr, '%val' );
        $builder->build_ret( $builder->build_sext( $val, $i64, '%ext' ) );
        my $codegen     = $brocken->codegen;
        my $bytes       = $codegen->emit_function($func);
        ok( length($bytes) > 0, 'i32 neg: generated bytes' );
        my $output_file = $brocken->tmpdir . '/width_i32_neg' . $brocken->ext;
        $brocken->linker->write_executable( $output_file, $bytes, $platform );
        run_exec( $output_file, expected_exit => 0xFF, platform => $platform, name => 'i32 sext -1 returned 255' );
    }
};

subtest 'i1 bool alloca / store true / load / zext / return' => sub {
    SKIP: {
        skip 'Execution test only supported on native hosts', 3 unless $platform->is_native;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i64 );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $ptr = $builder->build_alloca( $i1, '%ptr' );
        $builder->build_store( Brocken::Lindsay::IR::Constant->new( type => $i1, value => 1 ), $ptr );
        my $val = $builder->build_load( $i1, $ptr, '%val' );
        $builder->build_ret( $builder->build_zext( $val, $i64, '%ext' ) );
        my $codegen     = $brocken->codegen;
        my $bytes       = $codegen->emit_function($func);
        ok( length($bytes) > 0, 'i1 true: generated bytes' );
        my $output_file = $brocken->tmpdir . '/width_i1_true' . $brocken->ext;
        $brocken->linker->write_executable( $output_file, $bytes, $platform );
        run_exec( $output_file, expected_exit => 1, platform => $platform, name => 'i1 true returned 1 (not 255)' );
    }
};

subtest 'i1 bool alloca / store false / load / zext / return' => sub {
    SKIP: {
        skip 'Execution test only supported on native hosts', 3 unless $platform->is_native;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i64 );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $ptr = $builder->build_alloca( $i1, '%ptr' );
        $builder->build_store( Brocken::Lindsay::IR::Constant->new( type => $i1, value => 0 ), $ptr );
        my $val = $builder->build_load( $i1, $ptr, '%val' );
        $builder->build_ret( $builder->build_zext( $val, $i64, '%ext' ) );
        my $codegen     = $brocken->codegen;
        my $bytes       = $codegen->emit_function($func);
        ok( length($bytes) > 0, 'i1 false: generated bytes' );
        my $output_file = $brocken->tmpdir . '/width_i1_false' . $brocken->ext;
        $brocken->linker->write_executable( $output_file, $bytes, $platform );
        run_exec( $output_file, expected_exit => 0, platform => $platform, name => 'i1 false returned 0' );
    }
};

subtest 'Mixed width: i64 value truncated to i8 alloca' => sub {
    SKIP: {
        skip 'Execution test only supported on native hosts', 3 unless $platform->is_native;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i64 );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $ptr = $builder->build_alloca( $i8, '%ptr' );
        $builder->build_store( Brocken::Lindsay::IR::Constant->new( type => $i64, value => 256 ), $ptr );
        my $val = $builder->build_load( $i8, $ptr, '%val' );
        $builder->build_ret( $builder->build_zext( $val, $i64, '%ext' ) );
        my $codegen     = $brocken->codegen;
        my $bytes       = $codegen->emit_function($func);
        ok( length($bytes) > 0, 'i8 trunc: generated bytes' );
        my $output_file = $brocken->tmpdir . '/width_i8_trunc' . $brocken->ext;
        $brocken->linker->write_executable( $output_file, $bytes, $platform );
        run_exec( $output_file, expected_exit => 0, platform => $platform, name => 'i64 256 stored to i8 returns 0 (low byte)' );
    }
};

subtest 'Mixed width: i64 value truncated to i16 alloca' => sub {
    SKIP: {
        skip 'Execution test only supported on native hosts', 3 unless $platform->is_native;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i64 );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $ptr = $builder->build_alloca( $i16, '%ptr' );
        $builder->build_store( Brocken::Lindsay::IR::Constant->new( type => $i64, value => 0x10001 ), $ptr );
        my $val = $builder->build_load( $i16, $ptr, '%val' );
        $builder->build_ret( $builder->build_zext( $val, $i64, '%ext' ) );
        my $codegen     = $brocken->codegen;
        my $bytes       = $codegen->emit_function($func);
        ok( length($bytes) > 0, 'i16 trunc: generated bytes' );
        my $output_file = $brocken->tmpdir . '/width_i16_trunc' . $brocken->ext;
        $brocken->linker->write_executable( $output_file, $bytes, $platform );
        run_exec( $output_file, expected_exit => 1, platform => $platform, name => 'i64 0x10001 stored to i16 returns 1 (low word)' );
    }
};

subtest 'Mixed width: i64 value stored to i1 bool alloca truncates to LSB' => sub {
    SKIP: {
        skip 'Execution test only supported on native hosts', 3 unless $platform->is_native;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i64 );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $ptr = $builder->build_alloca( $i1, '%ptr' );
        $builder->build_store( Brocken::Lindsay::IR::Constant->new( type => $i64, value => 3 ), $ptr );
        my $val = $builder->build_load( $i1, $ptr, '%val' );
        $builder->build_ret( $builder->build_zext( $val, $i64, '%ext' ) );
        my $codegen     = $brocken->codegen;
        my $bytes       = $codegen->emit_function($func);
        ok( length($bytes) > 0, 'i1 trunc: generated bytes' );
        my $output_file = $brocken->tmpdir . '/width_i1_trunc' . $brocken->ext;
        $brocken->linker->write_executable( $output_file, $bytes, $platform );
        run_exec( $output_file, expected_exit => 3, platform => $platform, name => 'i64 3 stored to i1 returns 3 (1-byte store, all 8 bits preserved)' );
    }
};

subtest 'i32 max value round-trip (low byte)' => sub {
    SKIP: {
        skip 'Execution test only supported on native hosts', 3 unless $platform->is_native;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i64 );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $ptr = $builder->build_alloca( $i32, '%ptr' );
        $builder->build_store( Brocken::Lindsay::IR::Constant->new( type => $i32, value => 0x7FFFFFFF ), $ptr );
        my $val = $builder->build_load( $i32, $ptr, '%val' );
        $builder->build_ret( $builder->build_zext( $val, $i64, '%ext' ) );
        my $codegen     = $brocken->codegen;
        my $bytes       = $codegen->emit_function($func);
        ok( length($bytes) > 0, 'i32 max: generated bytes' );
        my $output_file = $brocken->tmpdir . '/width_i32_max' . $brocken->ext;
        $brocken->linker->write_executable( $output_file, $bytes, $platform );
        run_exec( $output_file, expected_exit => ( 0x7FFFFFFF & 0xFF ), platform => $platform, name => 'i32 0x7FFFFFFF low byte' );
    }
};

subtest 'i16 max value round-trip (low byte)' => sub {
    SKIP: {
        skip 'Execution test only supported on native hosts', 3 unless $platform->is_native;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i64 );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $ptr = $builder->build_alloca( $i16, '%ptr' );
        $builder->build_store( Brocken::Lindsay::IR::Constant->new( type => $i16, value => 0x7FFF ), $ptr );
        my $val = $builder->build_load( $i16, $ptr, '%val' );
        $builder->build_ret( $builder->build_zext( $val, $i64, '%ext' ) );
        my $codegen     = $brocken->codegen;
        my $bytes       = $codegen->emit_function($func);
        ok( length($bytes) > 0, 'i16 max: generated bytes' );
        my $output_file = $brocken->tmpdir . '/width_i16_max' . $brocken->ext;
        $brocken->linker->write_executable( $output_file, $bytes, $platform );
        run_exec( $output_file, expected_exit => ( 0x7FFF & 0xFF ), platform => $platform, name => 'i16 0x7FFF low byte' );
    }
};

subtest 'i1 load+zext chain gives correct result' => sub {
    SKIP: {
        skip 'Execution test only supported on native hosts', 3 unless $platform->is_native;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i64 );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $p1 = $builder->build_alloca( $i1, '%p1' );
        my $p2 = $builder->build_alloca( $i1, '%p2' );
        $builder->build_store( Brocken::Lindsay::IR::Constant->new( type => $i1, value => 1 ), $p1 );
        $builder->build_store( Brocken::Lindsay::IR::Constant->new( type => $i1, value => 0 ), $p2 );
        my $v1 = $builder->build_load( $i1, $p1, '%v1' );
        my $v2 = $builder->build_load( $i1, $p2, '%v2' );
        my $and = $builder->build_and( $v1, $v2, '%and' );
        $builder->build_ret( $builder->build_zext( $and, $i64, '%ext' ) );
        my $codegen     = $brocken->codegen;
        my $bytes       = $codegen->emit_function($func);
        ok( length($bytes) > 0, 'i1 bool chain: generated bytes' );
        my $output_file = $brocken->tmpdir . '/width_i1_chain' . $brocken->ext;
        $brocken->linker->write_executable( $output_file, $bytes, $platform );
        run_exec( $output_file, expected_exit => 0, platform => $platform, name => 'true AND false = 0' );
    }
};

subtest 'i8 signed negative store/load/sext' => sub {
    SKIP: {
        skip 'Execution test only supported on native hosts', 3 unless $platform->is_native;
        my $func    = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i64 );
        my $builder = Brocken::Lindsay::IR::Builder->new();
        $builder->position_at_end( $func->append_block('entry') );
        my $ptr = $builder->build_alloca( $i8, '%ptr' );
        $builder->build_store( Brocken::Lindsay::IR::Constant->new( type => $i8, value => -1 ), $ptr );
        my $val = $builder->build_load( $i8, $ptr, '%val' );
        $builder->build_ret( $builder->build_sext( $val, $i64, '%ext' ) );
        my $codegen     = $brocken->codegen;
        my $bytes       = $codegen->emit_function($func);
        ok( length($bytes) > 0, 'i8 neg: generated bytes' );
        my $output_file = $brocken->tmpdir . '/width_i8_neg' . $brocken->ext;
        $brocken->linker->write_executable( $output_file, $bytes, $platform );
        run_exec( $output_file, expected_exit => 0xFF, platform => $platform, name => 'i8 sext -1 returned 255' );
    }
};

done_testing;
