=pod

=encoding utf-8

=head1 NAME

Brocken::Lindsay::IR - High-Level Intermediate Representation Types

=head1 DESCRIPTION

Defines the core data structures for Brocken's SSA-form intermediate representation. The IR is LLVM-inspired and uses
an SSA representation with typed values, instructions, basic blocks, functions, and modules.

=head2 Type System

Types are represented as singleton objects via the L<Brocken::Lindsay::IR::Type> class. Common types (i1, i8, i32, i64,
f32, f64, ptr, void, dynamic) are created once and cached.

=head2 Value Hierarchy

=over

=item L<Brocken::Lindsay::IR::Value> - Base class for all IR values

=item L<Brocken::Lindsay::IR::Constant> - Constant values (literals)

=item L<Brocken::Lindsay::IR::Instruction> - Base instruction class

=back

=head2 Instruction Types

=over

=item B<Arithmetic>: add, sub, mul, div, rem, neg, abs, sqrt, shl, lshr, ashr, and, or, xor, min, max

=item B<Comparison>: icmp (eq, ne, sgt, slt, etc.)

=item B<Memory>: alloca, load, store, getelementptr

=item B<Control flow>: br, cond_br, ret, call, select, phi

=item B<Runtime>: box, unbox, incref, decref

=back

=head2 Program Structure

=over

=item L<Brocken::Lindsay::IR::Module> - Top-level container of functions

=item L<Brocken::Lindsay::IR::Function> - Function with params, return type, and blocks

=item L<Brocken::Lindsay::IR::Block> - Basic block containing a sequence of instructions

=back


=head1 LICENSE & LEGAL

This software is Copyright (c) 2026 by Sanko Robinson.

This is free software. You may use, copy, modify, and distribute it under the terms of either of the following
licenses, at your option:

  The Artistic License 2.0 (GPL Compatible) - see F<LICENSE-A2>

  The MIT License (GPL Compatible) - see F<LICENSE-MIT>

The documentation, including the code examples in it, is licensed under the Creative Commons Attribution 4.0
International license, see F<LICENSE-CC>, when it is used apart from the code.


=head1 AUTHOR

Sanko Robinson - L<https://github.com/sanko>


=cut
