=pod

=encoding utf-8

=head1 NAME

Brocken::Jenny::Linker - Unified Binary Executable Generator

=head1 DESCRIPTION

The Linker class provides a platform-agnostic interface for taking machine code and data segments and packaging them
into a final executable or shared library.



=head1 LICENSE & LEGAL

This software is Copyright (c) 2026 by Sanko Robinson.

This is free software. You may use, copy, modify, and distribute it under the terms of either of the following
licenses, at your option:

  The Artistic License 2.0 (GPL Compatible) - see F<LICENSE-A2>

  The MIT License (GPL Compatible) - see F<LICENSE-MIT>

The documentation, including the code examples in it, is licensed under the Creative Commons Attribution 4.0
International license, see F<LICENSE-CC>, when it is used apart from the code.


=head1 AUTHOR

Sanko Robinson - L<https://github.com/sanko>


=cut
