=pod

=encoding utf-8

=head1 NAME

Test2::Tools::Brocken - Test Utility for Running Compiled Executables

=head1 DESCRIPTION

Provides the C<run_exec> function for testing compiled Brocken executables within the Test2 test framework. Handles
running the binary, checking the exit code, and optionally debugging with GDB.

=head1 FUNCTIONS

=head2 C<run_exec( ... )>

    run_exec($file, %args);

Runs a compiled executable and checks its exit code.

=head3 Arguments

=over

=item C<file> - Path to the compiled executable

=item C<expected_exit> - Expected exit code (required for assertions)

=item C<name> - Test name for Test2 output

=item C<platform> - L<Brocken::Katsuro::Platform> object (for path separators)

=item C<gdb> - If true, run under GDB for debugging

=item C<keep> - If true, do not delete the executable after the test

=item C<args> - Arrayref of command-line arguments to pass

=back


=head1 LICENSE & LEGAL

This software is Copyright (c) 2026 by Sanko Robinson.

This is free software. You may use, copy, modify, and distribute it under the terms of either of the following
licenses, at your option:

  The Artistic License 2.0 (GPL Compatible) - see F<LICENSE-A2>

  The MIT License (GPL Compatible) - see F<LICENSE-MIT>

The documentation, including the code examples in it, is licensed under the Creative Commons Attribution 4.0
International license, see F<LICENSE-CC>, when it is used apart from the code.


=head1 AUTHOR

Sanko Robinson - L<https://github.com/sanko>


=cut
