# This file is auto-generated by bin/gen_icb.pl from etc/icb_layout.pl.
# Do not edit manually. Run: perl bin/gen_icb.pl
package Brocken::ICB;
use v5.42;
use strict;
use warnings;
use constant {
    HEAP_CURSOR         => 0,
    CURRENT_FCB         => 8,
    FIBER_HEAD          => 16,
    IMMIX_CURSOR        => 24,
    IMMIX_LIMIT         => 32,
    FREE_BLOCKS         => 40,
    FREE16_HEAD         => 48,
    SUSPECT_BUFFER_HEAD => 56,
    FUEL                => 64,
    ERR_CODE            => 72,
    CURRENT_BLOCK       => 80,
    MEMORY_LIMIT        => 88,
    MEMORY_USED         => 96,
    CAPABILITIES        => 104,
    SIZE                => 112,
    ERR_NO_FUEL         => 2,
    ERR_OK              => 0,
    ERR_OOM             => 1,
    ERR_SECURITY        => 3,
};
use Exporter 'import';
our @EXPORT_OK
    = qw(HEAP_CURSOR CURRENT_FCB FIBER_HEAD IMMIX_CURSOR IMMIX_LIMIT FREE_BLOCKS FREE16_HEAD SUSPECT_BUFFER_HEAD FUEL ERR_CODE CURRENT_BLOCK MEMORY_LIMIT MEMORY_USED CAPABILITIES SIZE ERR_NO_FUEL ERR_OK ERR_OOM ERR_SECURITY);
1;
