use v5.42;
use Test2::V0 '!subtest';
use Test2::Util::Importer 'Test2::Tools::Subtest' => ( subtest_streamed => { -as => 'subtest' } );
use lib 'lib', '../../../lib', '../../lib', '../lib';
use Test2::Tools::Brocken qw[run_exec];
use Brocken;
use Brocken::Lindsay;
no warnings qw[experimental::class experimental::builtin portable];
use feature qw[class];
SKIP: {
    my $brocken = Brocken->new();
    my $host    = $brocken->platform;
    skip 'M:N threading test only on native hosts', 1 unless $host->is_native;
    my $i32 = Brocken::Lindsay::IR::Type::i32();
    my $i64 = Brocken::Lindsay::IR::Type::i64();
    subtest 'Two workers each with a fiber' => sub {
        my $fiber_fn = Brocken::Lindsay::IR::Function->new( name => 'fiber_fn', return_type => $i32 );
        my $fb       = Brocken::Lindsay::IR::Builder->new();
        $fb->position_at_end( $fiber_fn->append_block('entry') );
        $fb->build_fiber_yield( Brocken::Lindsay::IR::Constant->new( type => $i64, value => 1 ), '%yv' );
        my $worker1 = Brocken::Lindsay::IR::Function->new( name => 'worker1', return_type => $i32 );
        my $w1b     = Brocken::Lindsay::IR::Builder->new();
        $w1b->position_at_end( $worker1->append_block('entry') );
        my $fcb1 = $w1b->build_fiber_create( $fiber_fn, [], '%fcb1' );
        $w1b->build_fiber_pin( $fcb1, Brocken::Lindsay::IR::Constant->new( type => $i64, value => 1 ) );
        $w1b->build_fiber_transfer( $fcb1, Brocken::Lindsay::IR::Constant->new( type => $i64, value => 1 ), '%r1' );
        $w1b->build_ret( Brocken::Lindsay::IR::Constant->new( type => $i32, value => 55 ) );
        my $worker2 = Brocken::Lindsay::IR::Function->new( name => 'worker2', return_type => $i32 );
        my $w2b     = Brocken::Lindsay::IR::Builder->new();
        $w2b->position_at_end( $worker2->append_block('entry') );
        my $fcb2 = $w2b->build_fiber_create( $fiber_fn, [], '%fcb2' );
        $w2b->build_fiber_pin( $fcb2, Brocken::Lindsay::IR::Constant->new( type => $i64, value => 1 ) );
        $w2b->build_fiber_transfer( $fcb2, Brocken::Lindsay::IR::Constant->new( type => $i64, value => 1 ), '%r2' );
        $w2b->build_ret( Brocken::Lindsay::IR::Constant->new( type => $i32, value => 66 ) );
        my $main = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i32 );
        my $mb   = Brocken::Lindsay::IR::Builder->new();
        $mb->position_at_end( $main->append_block('entry') );
        my $iso1 = $mb->build_isolate_create( $worker1, [], '%iso1' );
        my $iso2 = $mb->build_isolate_create( $worker2, [], '%iso2' );
        my $r1   = $mb->build_isolate_join( $iso1, '%r1' );
        my $r2   = $mb->build_isolate_join( $iso2, '%r2' );
        my $sum  = $mb->build_add( $r1, $r2, '%sum' );
        $mb->build_ret($sum);
        my $funcs = $brocken->codegen->emit_functions( [ $main, $worker1, $worker2, $fiber_fn ] );
        my $file  = $brocken->tmpdir . '/mn_two_workers' . $brocken->ext;
        $brocken->linker->write_executable( $file, $funcs, $host );
        my $dbg = $host->is_dragonflybsd || $host->is_netbsd ? 1 : 0;
        run_exec( $file, expected_exit => 121, name => 'two workers sum 121', platform => $host, keep => 1, gdb => $dbg );
    };
    subtest 'Three workers with chained fiber transfers' => sub {
        my $fiber_fn = Brocken::Lindsay::IR::Function->new( name => 'fiber_fn', return_type => $i32 );
        my $fb       = Brocken::Lindsay::IR::Builder->new();
        $fb->position_at_end( $fiber_fn->append_block('entry') );
        $fb->build_fiber_yield( Brocken::Lindsay::IR::Constant->new( type => $i64, value => 1 ), '%yv' );
        $fb->build_fiber_yield( Brocken::Lindsay::IR::Constant->new( type => $i64, value => 2 ), '%yv2' );
        my $worker_fn = Brocken::Lindsay::IR::Function->new( name => 'wf', return_type => $i32 );
        my $wb        = Brocken::Lindsay::IR::Builder->new();
        $wb->position_at_end( $worker_fn->append_block('entry') );
        my $fcb = $wb->build_fiber_create( $fiber_fn, [], '%fcb' );
        $wb->build_fiber_pin( $fcb, Brocken::Lindsay::IR::Constant->new( type => $i64, value => 1 ) );
        $wb->build_fiber_transfer( $fcb, Brocken::Lindsay::IR::Constant->new( type => $i64, value => 1 ), '%r1' );
        $wb->build_fiber_transfer( $fcb, Brocken::Lindsay::IR::Constant->new( type => $i64, value => 2 ), '%r2' );
        $wb->build_ret( Brocken::Lindsay::IR::Constant->new( type => $i32, value => 80 ) );
        my $main = Brocken::Lindsay::IR::Function->new( name => 'main', return_type => $i32 );
        my $mb   = Brocken::Lindsay::IR::Builder->new();
        $mb->position_at_end( $main->append_block('entry') );
        my $i1 = $mb->build_isolate_create( $worker_fn, [], '%i1' );
        my $i2 = $mb->build_isolate_create( $worker_fn, [], '%i2' );
        my $i3 = $mb->build_isolate_create( $worker_fn, [], '%i3' );
        my $r1 = $mb->build_isolate_join( $i1, '%r1' );
        my $r2 = $mb->build_isolate_join( $i2, '%r2' );
        my $r3 = $mb->build_isolate_join( $i3, '%r3' );
        my $t1 = $mb->build_add( $r1, $r2, '%t1' );
        my $t2 = $mb->build_add( $t1, $r3, '%t2' );
        $mb->build_ret($t2);
        my $funcs = $brocken->codegen->emit_functions( [ $main, $worker_fn, $fiber_fn ] );
        my $file  = $brocken->tmpdir . '/mn_three_workers' . $brocken->ext;
        $brocken->linker->write_executable( $file, $funcs, $host );
        my $dbg = $host->is_dragonflybsd || $host->is_netbsd ? 1 : 0;
        run_exec( $file, expected_exit => 240, name => 'three workers sum 240', platform => $host, keep => 1, gdb => $dbg );
    };
}
done_testing;
