---
jobs:
  build:
    name: "[${{ inputs.arch }}] ${{ inputs.os == 'freebsd' && 'FreeBSD' ||  inputs.os == 'openbsd' && 'OpenBSD' || inputs.os }} ${{ inputs.version }}"
    runs-on: '${{ inputs.host }}'
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          submodules: true
      - env:
          AUTHOR_TESTING: 0
          AUTOMATED_TESTING: 1
        name: 'Test on ${{ inputs.os }}'
        uses: cross-platform-actions/action@v0.32.0
        with:
          architecture: '${{ inputs.arch }}'
          cpu_count: 4
          environment_variables: AUTHOR_TESTING AUTOMATED_TESTING
          memory: 5G
          operating_system: '${{ inputs.os }}'
          run: |
            uname -a
            ${{ inputs.setup }}
            sudo ${{inputs.pkg}} perl5
            perl -v
            perl demo.pl linux
          shell: bash
          version: '${{ inputs.version }}'
name: bsd module
on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      host:
        required: true
        type: string
      os:
        required: true
        type: string
      perl:
        required: true
        type: string
      perl_subversion:
        default: 2
        required: false
        type: string
      pkg:
        required: true
        type: string
      setup:
        default: ''
        required: false
        type: string
      version:
        required: true
        type: string
