---
jobs:
  build:
    name: "${{ inputs.flags == '-Dusethreads' && 'Strawberry' || 'Default' }}"
    runs-on: '${{ inputs.os }}'
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          submodules: true
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1.40.0
        with:
          distribution: "${{ inputs.flags == '-Dusethreads' && 'strawberry' || 'default' }}"
          multi-thread: "${{ inputs.flags == '-Dusethreads' && true || false }}"
          perl-version: '${{ inputs.perl }}'
      - name: Run Pulse Script
        run: |
          perl -V
          perl demo.pl win64
name: windows module
on:
  workflow_call:
    inputs:
      flags:
        required: false
        type: string
      os:
        required: true
        type: string
      perl:
        required: true
        type: string
